import { PageLoading } from "@/components/elements/loading";
import { Navbar } from "@/components/modules/Navbar";
import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="flex flex-col h-screen w-full overflow-hidden">
        <Navbar />
        <Suspense fallback={<PageLoading text="Loading application..." />}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
