import { Navbar } from "@/components/modules/navbar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <main className="flex h-screen flex-col w-full">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
